petrofit/correction.py
petrofit/models.py
petrofit/petrosian.py
petrofit/photometry.py
petrofit/utils.py

Edits to the code based on testing while writing the paper

paper related patch 

---

README.rst
docs/index.rst

Response to first paper review.

Paper review related fixes

---

.circleci/config.yml

Upgrade resource_class to `medium+`

upgrade circleci resource_class

---

docs/index.rst
docs/release_procedure.rst

close #54 
This PR add release steps to docs.

Add Release Procedure

---

petrofit/fitting.py

fix odd size model bug

---

CHANGES.md

Last minute updates for v0.3.1

Prep for v0.3.1

---

docs/fitting.ipynb
docs/multi_object.ipynb
docs/photometry_and_petrosian.ipynb

Background fitting code changed, changing docs to reflect change.

Doc patch background fitting 

---

docs/index.rst
docs/quick_start.ipynb
petrofit/models.py

Sérsic Model Bounds and Quick Start Guide

---

CHANGES.md
petrofit/utils.py

Remove `petrofit.utils.cutout`

---

CHANGES.md
environment.yml

Prep for v0.4.0

---

README.rst
docs/index.rst

Add `keywords` metadata for docs

---

docs/index.rst

Improve RTD indexing on Google using Google Search Console

SEO Enhancement 

---

docs/index.rst
docs/introduction.ipynb
docs/multi_object.ipynb
tox.ini

Change heading "Advanced" to "Tutorials". Also enable warning fails for doc build tests.

Docs: Change "Advanced" -> "Tutorials"

---

CHANGES.md
petrofit/modeling/models.py
requirements.txt

closes #141
This PR adds:
- Add `regions` to requirements.
- Add `GenSersic2D` model, which is a Sersic model with generalized ellipse isophot (boxy) parameter.
- Bug Fix: Model attribute bug fix in  `PSFConvolvedModel2D`. 
- Print out PSF sum if it is not equal to 1.

`GenSersic2D` and bug fixes 

---

docs/installation.rst
docs/release_procedure.rst
environment.yml

closes #121 
- Add `petrofit_environments` repo info
- Fix: remove env file STIPS ref.

Doc updates 

---

CHANGES.md
petrofit/segmentation.py

closes #132 
Simple bug fix, see #132

Change `make_catalog` `kernel_size` parameter to odd number

---

CHANGES.md

Prep for v0.4.1

---

petrofit/modeling/models.py

Example from Astropy `Sersic2D` doc-string was causing issues.

Remove example from astropy in GenSersic2D

---

.github/workflows/ci_tests.yml
README.rst

add badge for CI, which was introduced in #181

add GitHub CI badge

---

docs/fitting.ipynb
docs/quick_start.ipynb
petrofit/modeling/fitting.py
petrofit/modeling/models.py
petrofit/petrosian/correction.py
petrofit/tests/test_petrosian.py
tox.ini

closes #176 , closes #137, closes #180
- Introduce `TRFLSQFitter` as the default fitter. 
- Allow users to choose fitters.
- Enable `calc_uncertainties`.
- Oversampled PSF.

Fitting upgrades [v0.5.0]

---

petrofit/petrosian/correction.py

Fix plot strings

---

requirements.txt

Update Photuitls and Astropy versions

---

CHANGES.md

Prep for v0.5.0

---

CHANGES.md
environment.yml
requirements.txt
setup.cfg
tox.ini

This PR updates requirements for python 3.12 compat.

update Infrastructure and python version 3.12+

---

docs/correction_grids.ipynb
docs/fitting.ipynb
docs/fitting_workflow.ipynb
docs/introduction.ipynb
docs/multi_object.ipynb
docs/petrosian.ipynb
docs/photometry.ipynb
docs/quick_start.ipynb
petrofit/modeling/fitting.py
petrofit/petrosian/core.py
petrofit/photometry.py
petrofit/segmentation.py

Collecting typo and similar very minor fixes as I notice them during my PyOpenSci review.

Misc fixes noticed during PyOpenSci review

---

README.rst
petrofit/conftest.py
petrofit/modeling/fitting.py
petrofit/modeling/models.py
petrofit/petrosian/core.py
petrofit/petrosian/correction.py
petrofit/photometry.py
petrofit/segmentation.py
petrofit/tests/conftest.py
petrofit/tests/test_fitting.py
petrofit/tests/test_petrosian.py
petrofit/tests/test_photometry.py
petrofit/tests/test_segmentation.py
petrofit/tests/test_utils.py
petrofit/utils.py

This PR fixes formatting of codebase

Run Black Formatting on Codebase

---

.github/workflows/test.yml
README.rst

Add coverage test

---

.github/ISSUE_TEMPLATE/01-bug-report.yml
.github/ISSUE_TEMPLATE/03-feature-request.yml
.github/SUPPORT.md
CITATION.rst
README.rst
docs/installation.rst
pyproject.toml

closes #223 
closes #224 
Minor fixes to README and Citations

Clean up README and Citation

---

CHANGES.md
README.rst

This PR adds Generative AI Policy

Generative AI Policy

---

petrofit/modeling/models.py
petrofit/petrosian/core.py
petrofit/petrosian/correction.py
petrofit/utils.py

This PR adds missing docstrings to the package and remove the outdated function `_dr_old`

Add Missing Docstrings and remove `_dr_old `

---

README.rst

Small edit to add pyOpenSci tag.

add pyOpenSci tag

---

CHANGES.md

*March 3rd 2025*
These significant changes are in light of the pyOpenSci review process. These changes primarily focus on the packaging and installation infrastructure. These enhancements do not impact the core codebase directly.
**PetroFit Enhancements**
- Transition to Hatch: Migrated from `setuptools` to `hatch` for streamlined packaging and dependency management. #209
- Configuration Enhancements #209:
- Added `.editorconfig` to standardize code style across different editors.
- Introduced GitHub issue templates in `.github/ISSUE_TEMPLATE` for consistent issue reporting.
- Updated test workflow to utilize `hatch` for test environment setup.
- Docker Removal #209:
- Removed Docker support, including deletion of the Dockerfile and the `docker.py` helper script.
- Legacy Files #209:
- …

Prep for v0.6.0
